---
version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    environment:
      - REACT_APP_API_URL=http://ec2-3-140-251-80.us-east-2.compute.amazonaws.com:5000
      - PORT=3001
    tty: true
    ports:
      - 3001:3001
    volumes:
      - .:/app